services:
  - type: web
    name: kavach-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node start-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: APIFY_API_KEY  
        sync: false
      - key: ALLOWED_ORIGINS
        value: "chrome-extension://*,https://www.google.com,https://www.facebook.com,https://www.amazon.com"
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "1000"
    healthCheckPath: /health
    healthCheckPath: /health
